/**
 * Enumerates every IPC channel exposed by AI Media Studio.
 */

export enum IpcChannel {
  AppBootstrap = 'app:bootstrap',
  SettingsSave = 'settings:save',
  CredentialsSave = 'credentials:save',
  CredentialsGet = 'credentials:get',
  CredentialsDelete = 'credentials:delete',
  CredentialsBalance = 'credentials:balance',
  ModelsGet = 'models:get',
  ReferencesSelect = 'references:select',
  ReferencesRelease = 'references:release',
  AudioInputSelect = 'audio-input:select',
  AudioInputRelease = 'audio-input:release',
  GenerationStart = 'generation:start',
  SessionGet = 'session:get',
  SessionCreate = 'session:create',
  SessionRename = 'session:rename',
  SessionDelete = 'session:delete',
  SessionExport = 'session:export',
  MediaSave = 'media:save',
  MediaShowInFolder = 'media:show-in-folder',
  ClipboardWrite = 'clipboard:write',
  WindowAlwaysOnTop = 'window:always-on-top',
  WindowMinimize = 'window:minimize',
  WindowToggleMaximize = 'window:toggle-maximize',
  WindowClose = 'window:close',
  WindowIsMaximized = 'window:is-maximized',
  ThemeSet = 'theme:set',
  ShellOpenExternal = 'shell:open-external',
  LogsOpenDirectory = 'logs:open-directory',
  LogWrite = 'logs:write',
  UpdatesCheck = 'updates:check',
  UpdatesInstall = 'updates:install',
  SessionUpdated = 'event:session-updated',
  AppError = 'event:error',
  UpdateState = 'event:update-state',
  WindowMaximizedChanged = 'event:window-maximized-changed',
  SettingsOpenRequested = 'event:settings-open-requested',
}
